apiVersion: v1
clusters:
- cluster:
    insecure-skip-tls-verify: true
    server: https://172.16.70.57:8001
  name: ilon1
contexts:
- context:
    cluster: ilon1
    namespace: cert-manager
    user: user5
  name: ilon1-context
- context:
    cluster: ""
    namespace: namespace05
    user: ""
  name: mycluster-context
current-context: ilon1-context
kind: Config
preferences: {}
users:
- name: ilon1-user
  user:
    token: eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdF9oYXNoIjoiMmRjZGI3N2E1OTM1ZTk3MzE3YjUxYjlmOGIxMTE3NWM4ZGQ1ZGYzMyIsInJlYWxtTmFtZSI6ImN1c3RvbVJlYWxtIiwidW5pcXVlU2VjdXJpdHlOYW1lIjoidXNlcjUiLCJpc3MiOiJodHRwczovL2lsb24xLmljcDo5NDQzL29pZGMvZW5kcG9pbnQvT1AiLCJhdWQiOiJkMGIwOGIzZGQxYWUzM2FlNWRhNTE1YzQwZGRhYWZlYyIsImV4cCI6MTU1OTE0MjE3MCwiaWF0IjoxNTU5MTEzMzcwLCJzdWIiOiJ1c2VyNSIsInRlYW1Sb2xlTWFwcGluZ3MiOlsic3lzdGVtOm1hc3RlcnMiXX0.hbSE7FAY8iTg81F0EYrvW7jaLOLhY3fVUmQNND4MIv-Nn8thxpFBkPklgipYx8xMCbOYTB8ltPAXIdMUDcNB4v0fx0kL2M8JrN2ODc7doKJcbxEVQsu8lcf1rRscISnLIek6oezPW3nVfTq1E9LAa3OwiapnkTU6ijgQWpyJeXj0Pv2rZ7Y8FDlu8zI52zIy7h7aN6BIHN2Nn2sob2sVmeJLXba8F-TuNI0c3BZTtd_zXCqiSzJCqYifAyTxWOW5QlnG0SZUtLDXkguS7AErN_mk_b3feANuvuPTSkbq6wcglv9eqSU-4prOiW493rWK5IfPGDDoftqeEMb96akHdw
- name: user5
  user:
    token: eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdF9oYXNoIjoiMTg0ZDA4YWY0MTU5YzllZjQ3NjMxNDNkM2RkNTgxMTc0MGE2ZjkxOSIsInJlYWxtTmFtZSI6ImN1c3RvbVJlYWxtIiwidW5pcXVlU2VjdXJpdHlOYW1lIjoidXNlcjUiLCJpc3MiOiJodHRwczovL2lsb24xLmljcDo5NDQzL29pZGMvZW5kcG9pbnQvT1AiLCJhdWQiOiJkMGIwOGIzZGQxYWUzM2FlNWRhNTE1YzQwZGRhYWZlYyIsImV4cCI6MTU1OTE1NTY0MSwiaWF0IjoxNTU5MTI2ODQxLCJzdWIiOiJ1c2VyNSIsInRlYW1Sb2xlTWFwcGluZ3MiOlsic3lzdGVtOm1hc3RlcnMiXX0.PlJOMjU5Xp8XJ-Sn6BciNm9lVfl_oF4hLHerB2lFY2uy81Z3fwtCFlutkaZFsK6IzSNq0J0wNVI-u7ugdvDzssbX9nopj8xx-GljdK3UPgW6EUlb7TriEzPFbtEhS0134uHpy0c8utu062n4CqjjUm4qTzHwXkfcnjIVKSr0uLFRsP0NEh0FFK718uuIVpirkmMVJ-M52rcGPP-wicYZTEa66nTHrXOh-L3aOUyBmmbnosCvT_4secYqQp6JCacwEHqv9HpAH7JIxOGyTUiwNFySBrPGLxFayNWFBRPyDCU-aker9cWh-775uZ8PbIyDn435EaQMBi79ITbf7dIf_Q
